### ISSUE TITLE
보관함 화면

### ISSUE THREAD

**Issue by stellarbg** [Team-PatPat/PatPat-Android#31]
### Todo

- [x] 보관함 화면 ui 구현
- [x] 서버로 부터 데이터 받아오기
- [x] 보관함에 있는 편지 클릭시 전체 내용 보여주기
